[package]
name = "tauri-plugin-bin-ipc"
version = "0.0.0"
authors = ["maemon4095"]
description = "binary ipc via custom protocol"
edition = "2021"
rust-version = "1.60"
exclude = ["/examples"]

[dependencies]
tauri = { version = "1.6.1" }
