[package]
name = "msgpack-macro-test"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
tauri-plugin-bin-ipc = { path = "../..", features = ["default-msgpack"] }
tauri.workspace = true
